name: Run unit tests
on:
  - pull_request
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: proget.hunterwittenborn.com/docker/makedeb/makedeb:ubuntu-lunar
      options: --user root
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Setup makedeb APT repositories
        uses: makedeb/setup-makedeb@main
        with:
          pbmpr-repo: true
      - name: Install needed APT packages
        run: |
          # Set the directory permissions to be correct so it can be used correctly by makedeb.
          chown 'makedeb:makedeb' makedeb/ -R

          # Get our needed dependencies by just sourcing them from the PKGBUILD.
          echo 'build() { true; }; package() { true; }; source=(); sha256sums=()' >> makedeb/PKGBUILD
          cd makedeb && sudo -u makedeb makedeb -s --no-confirm
      - name: Run formatting checks
        run: cargo fmt --check
      - name: Run Clippy checks
        run: just clippy
